### ISSUE TITLE
Webresource content size is too big

### ISSUE THREAD

**Issue by Belleye** [cchannon/BasicDataGridForCanvas#2]
Looks like a great project.

Built from source. When running pac pcf push I get the following message: 

Error: Import Solution Failed: CustomControl with name ktcs.BasicGridForCanvas failed to import with error: Webresource content size is too big.
Import Solution Failed: CustomControl with name ktcs.BasicGridForCanvas failed to import with error: Webresource content size is too big.

**Comment by LarryBambelle** [comment]
Hey, 

This is caused by your default environnment settings: 

Go to, Advanced Settings -> Settings -> Administration -> System Settings
Then "Set file size limit for attachments" and increase this.

More details below
https://nebulaaitsolutions.com/blog/web-resource-content-size-is-too-big-in-pcf-control

**Comment by Belleye** [comment]
Thank you that worked :)
